import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request'
import BlogCard from "../components/BlogCard.js" 

const inter = Inter({ subsets: ['latin'] })

const graphcms = new GraphQLClient('https://api-eu-west-2.hygraph.com/v2/cleo2hy1i0r9201t8h227fuyw/master')

const QUERY = gql`
    {
      posts {
        title,
        date,
        slug,
        coverPhoto {
          url
        }
        content {
          html
        }
        author {
          name
          avatar {
            url
          }
        }
    }
  }
`
// fetches the data array and requests an update every 10 seconds
export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY)
  return {
    props: {
      posts,
    },
    revalidate: 10,
  }
}

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
            key={post.id}
            title={post.title}
            author={post.author}
            image={post.coverPhoto}
            date={post.date} 
            slug={post.slug} 
            content={post.content}    
          />
        ))}
      </main>
    </>
  )
}
